SQLite support
It's reporting "contains" isn't supported by `JSONField` so we'd need to overload it

See: https://github.com/django/django/blob/3.1.7/django/db/backends/sqlite3/features.py#L53

But also: https://github.com/django/django/blob/3.1.7/django/db/models/fields/json.py#L152-L164

```
======================================================================
FAIL: test_delete_object (nautobot.extras.tests.test_changelog.ChangeLogAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jathan/sandbox/src/nautobot/nautobot/extras/tests/test_changelog.py", line 265, in test_delete_object
    self.assertEqual(oc.object_data["tags"], ["Tag 1", "Tag 2"])
AssertionError: Lists differ: [] != ['Tag 1', 'Tag 2']

Second list contains 2 additional elements.
First extra element 0:
'Tag 1'

- []
+ ['Tag 1', 'Tag 2']
```

Not quite working yet. I think this error is related:

```
django.db.utils.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

See: https://sentry.io/share/issue/0fa7832eb33f4bc78b6526f98a9aeb70/